### PR TITLE
Upgrade to Octane

### PR DESCRIPTION
**Pull request by ryanone**
# Summary
This PR upgrades ember-a11y-accordion to Octane and Ember 3.26, addressing #13 

## Details
This was done in a 2-step approach

1. Upgrade to 3.12, refactoring tests, etc..
2. Upgrade to Octane and 3.26 - Functionality was refactored more or less as-is. The one "significant" change made is that I converted the SharedState to an ES6 class with tracked properties. This was for the purpose of getting away from `EmberObject`. I _could_ use a [Tracked Map](https://github.com/pzuraq/tracked-built-ins) which if there's a strong preference for, could be done in a subsequent PR. I also removed ember-native-dom-helpers, since `@ember/test-helpers` provides all the necessary functionality now.

### CODE REVIEW

**Comment by vasilionjea** [comment]
Thanks for the great PR! Soon I'll bump the version to `2.0.0` (previously `1.0.7`) and will publish the new version to NPM.

**Comment by ryanone** [comment]
Thanks @vasilionjea - Have you had the chance to publish a new version to NPM? Just want to follow-up on this. Thanks!

**Comment by vasilionjea** [comment]
@ryanone Apologies about the delay. I'll definitely have it published by Sunday, I just don't have my personal laptop with me for a few days as I'm traveling.

**Comment by vasilionjea** [comment]
Here is the new version: https://www.npmjs.com/package/ember-a11y-accordion Again thanks for the PR!

**Comment by ryanone** [comment]
Thanks!

**Pull request merged**
